---
framework: mocha
preRun:
     command:
        - npm install
preMerge:
  pattern:
    - "./test/*.js"
postMerge:
  pattern:
    - "./test/*.js"
postRun:
     command:
        - node --version
nodeVersion: 14.18
version: 1.0
