--- 
framework: mocha
nodeVersion: 14.18
postMerge: 
  pattern: 
    - ./test/*.js
postRun: 
  command: 
    - "node --version"
preMerge: 
  pattern: 
    - ./test/*.js
preRun: 
  command: 
    - "npm install"
version: 1.0
